# Generated by Django 3.1.7 on 2021-03-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('resumen', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('correo', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=9)),
                ('asuntoC', models.TextField()),
                ('asuntoW', models.TextField()),
            ],
        ),
    ]
