# Generated by Django 3.1.7 on 2021-03-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_conocimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrep', models.CharField(max_length=60)),
                ('descrip', models.TextField()),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
